### ISSUE TITLE
Hyderabad royal

### ISSUE THREAD

**Issue by hmnt94** [hmnt94/Hyderabad-Royal#1]
```yaml
name: Hyderabad Royal
key: Hyderabad
color: purple
track: true
emblem: Star_Shine_03
feature: true
vip: true
info:
  logo:cr-api-assets/badges/Star_Shine_03.png 
  description:  >
     **Started on January 9th,2016.One of the successful clans in Hyderabad.
 clans:
   -name: Hyderabad Royal
     tag:  22LQQY
   -name: Hyderabad Regal
     tag:  VQYPC99
```
